### ISSUE TITLE
Aplicação - Newtion 

### ISSUE THREAD

**Issue by thalees** [thalees/newtion#5]
##História

Está é apenas uma descrição do que deve ser realizado no projeto, acredito ser possível quebrar a aplicação em muuuito outros pontos, porém aqui está reporesentado o **macro do Newtion:**

### Todo

**User:** 
- [ ] Fazer cadastro do usuário 
- [ ] Autenticação do Login
- [ ] Pegar os interesses do usuário no **primeiro** Login

**New**
- [ ] Carregar a tela de notícias utilizando as APIs
- [ ] Possibilitar busca de notícias
- [ ] Carregar notícia para leitura ao ser clicada
- [ ] Possibilitar interação com a notícia ( _comentar , classificar, favoritar_ )
- [ ] Acessar a tela de configuração para edição de: _Perfil, Gostos, Fontes, Favoritos_
